services:
  firestarr:
    image: firestarr
    build:
      context: .
      target: firestarr
      dockerfile: .docker/Dockerfile
      tags:
        - firestarr:${VERSION}
    volumes:
      - type: bind
        source: ./settings.ini
        target: /appl/firestarr/settings.ini
      - ./test:/appl/firestarr/test:z
      - ./grid:/appl/firestarr/grid:z
      - ./data:/appl/data:z
    env_file:
      - .env

  firestarr-minimal:
    image: firestarr-minimal
    build:
      context: .
      target: firestarr-minimal
      dockerfile: .docker/Dockerfile
      tags:
        - firestarr-minimal:${VERSION}
    volumes:
      - type: bind
        source: ./settings.ini
        target: /appl/firestarr/settings.ini
      - ./test:/appl/firestarr/test:z
      - ./grid:/appl/firestarr/grid:z
      - ./data:/appl/data:z
    env_file:
      - .env

  firestarr-dev:
    image: firestarr-dev
    build:
      context: .
      target: firestarr-dev
      dockerfile: .docker/Dockerfile.dev
      tags:
        - firestarr-dev:${VERSION}
    entrypoint: tail -f /dev/null
    security_opt:
      - seccomp:unconfined
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - ~/.ssh:/home/user/.ssh
      - ./repo/.bash_aliases:/home/user/.bash_aliases
      - type: bind
        source: ./
        target: /appl/firestarr
      - ./data:/appl/data:z
    restart: always
    cap_add:
      - PERFMON
      - SYS_PTRACE
      - SYS_ADMIN
    env_file:
      - .env

  # HACK: so we can call cmake to update version
  firestarr-build:
    image: firestarr-build
    build:
      context: .
      target: firestarr-build
      dockerfile: .docker/Dockerfile
    entrypoint: /appl/firestarr/scripts/build.sh
    security_opt:
      - seccomp:unconfined
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - ~/.ssh:/home/user/.ssh
      - ./repo/.bash_aliases:/home/user/.bash_aliases
      - type: bind
        source: ./
        target: /appl/firestarr
      - ./data:/appl/data:z
    restart: never
