name: build-docker

on:
  push:
    paths-ignore:
      - '.github/workflows/cmake-test.yml'
      - '.github/workflows/docker-cleanup.yml'

  workflow_dispatch:

env:
  CONTAINER_REGISTRY: ghcr.io
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  # split this way so hopefully the cache is there between normal and minimal
  build-docker-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        # no point in more than base image supports
        # ignore 32-bit - 386, arm/v5, arm/v7
        # arm64 == arm64/v8
        platform: [amd64, arm64, ppc64le, riscv64, s390x]
        # platform: [amd64]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true

      - name: Prepare environment
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//}" >> $GITHUB_ENV
          registry=${{ env.CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY@L}
          image=${{ case( startsWith(github.ref, 'refs/tags/v') || contains('["main", "dev", "unstable"]', github.ref_name), 'firestarr', 'cache' ) }}
          echo "TARGET_CACHE=${registry}/cache:${platform//\//}" >> $GITHUB_ENV
          echo "TARGET=${registry}/${image}" >> $GITHUB_ENV
          echo "IMAGE=firestarr" >> $GITHUB_ENV

      - name: Login to container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: ${{ env.IMAGE }} - Docker meta
        id: meta-normal
        uses: docker/metadata-action@v6
        with:
          images: ${TARGET}

      - name: ${{ env.IMAGE }} - Build and push by digest
        id: build-normal
        uses: docker/build-push-action@v7
        with:
          context: .
          file: .docker/Dockerfile
          target: ${{ env.IMAGE }}
          platforms: linux/${{ matrix.platform }}
          labels: ${{ steps.meta-normal.outputs.labels }}
          tags: ${{ env.TARGET }}
          push: ${{ github.event_name != 'pull_request' }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          cache-from: |
            type=registry,ref=${{ env.TARGET_CACHE }}
          cache-to: |
            type=registry,mode=max,ref=${{ env.TARGET_CACHE }}

      - name: ${{ env.IMAGE }} - Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests-${{ env.IMAGE }}
          digest="${{ steps.build-normal.outputs.digest }}"
          touch "${{ runner.temp }}/digests-${{ env.IMAGE }}/${digest#sha256:}"

      - name: ${{ env.IMAGE }} - Upload digest
        uses: actions/upload-artifact@v7
        with:
          name: digests-firestarr-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests-${{ env.IMAGE }}/*
          if-no-files-found: error
          retention-days: 1

      - name: Change target image
        run: |
          echo "IMAGE=firestarr-minimal" >> $GITHUB_ENV

      - name: ${{ env.IMAGE }} - Docker meta
        id: meta-minimal
        uses: docker/metadata-action@v6
        with:
          images: ${TARGET}

      - name: ${{ env.IMAGE }} - Build and push by digest
        id: build-minimal
        uses: docker/build-push-action@v7
        with:
          context: .
          file: .docker/Dockerfile
          target: ${{ env.IMAGE }}
          platforms: linux/${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.TARGET }}
          labels: ${{ steps.meta-minimal.outputs.labels }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          cache-from: |
            type=registry,ref=${{ env.TARGET_CACHE }}
          cache-to: |
            type=registry,mode=max,ref=${{ env.TARGET_CACHE }}

      - name: ${{ env.IMAGE }} - Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests-${{ env.IMAGE }}
          digest="${{ steps.build-minimal.outputs.digest }}"
          touch "${{ runner.temp }}/digests-${{ env.IMAGE }}/${digest#sha256:}"

      - name: ${{ env.IMAGE }} - Upload digest
        uses: actions/upload-artifact@v7
        with:
          name: digests-${{ env.IMAGE }}-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests-${{ env.IMAGE }}/*
          if-no-files-found: error
          retention-days: 1

  merge-normal:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    needs: [ build-docker-image ]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true

      - name: Prepare environment
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//}" >> $GITHUB_ENV
          registry=${{ env.CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY@L}
          image=${{ case( startsWith(github.ref, 'refs/tags/v') || contains('["main", "dev", "unstable"]', github.ref_name), 'firestarr', 'cache' ) }}
          echo "TARGET_CACHE=${registry}/cache" >> $GITHUB_ENV
          echo "TARGET=${registry}/${image}" >> $GITHUB_ENV
          echo "IMAGE=firestarr" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: ${{ env.IMAGE }} - Download digests
        uses: actions/download-artifact@v8
        with:
          path: ${{ runner.temp }}/digests-${{ env.IMAGE }}
          pattern: digests-firestarr-*
          merge-multiple: true

      - name: ${{ env.IMAGE }} - Docker meta
        id: meta-normal
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.TARGET }}
          flavor: |
            latest=${{ case ( startsWith(github.ref, 'refs/tags/v'), 'auto', 'false' ) }}
            prefix=
            suffix=
          tags: |
            type=ref,event=pr
            type=ref,prefix=,suffix=,event=branch,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=ref,prefix=,suffix=-latest,event=branch,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{version}},prefix=,suffix=,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}}.{{minor}},prefix=,suffix=,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: ${{ env.IMAGE }} - Create manifest list and push
        working-directory: ${{ runner.temp }}/digests-${{ env.IMAGE }}
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.TARGET }}@sha256:%s ' *)

      - name: ${{ env.IMAGE }} - Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.TARGET }}:${{ steps.meta-normal.outputs.version }}

  merge-minimal:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    needs: [ build-docker-image ]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true

      - name: Prepare environment
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//}" >> $GITHUB_ENV
          registry=${{ env.CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY@L}
          image=${{ case( startsWith(github.ref, 'refs/tags/v') || contains('["main", "dev", "unstable"]', github.ref_name), 'firestarr', 'cache' ) }}
          echo "TARGET_CACHE=${registry}/cache" >> $GITHUB_ENV
          echo "TARGET=${registry}/${image}" >> $GITHUB_ENV
          echo "IMAGE=firestarr-minimal" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: ${{ env.IMAGE }} - Download digests
        uses: actions/download-artifact@v8
        with:
          path: ${{ runner.temp }}/digests-${{ env.IMAGE }}
          pattern: digests-${{ env.IMAGE }}-*
          merge-multiple: true

      - name: ${{ env.IMAGE }} - Docker meta
        id: meta-minimal
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.TARGET }}
          flavor: |
            latest=false
            prefix=
            suffix=-minimal
          tags: |
            type=ref,event=pr
            type=ref,prefix=,suffix=-minimal,event=branch,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=ref,prefix=,suffix=-minimal-latest,event=branch,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{version}},prefix=,suffix=-minimal,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}}.{{minor}},prefix=,suffix=-minimal,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=minimal,prefix=,suffix=,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=minimal-latest,prefix=,suffix=,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: ${{ env.IMAGE }} - Create manifest list and push
        working-directory: ${{ runner.temp }}/digests-${{ env.IMAGE }}
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.TARGET }}@sha256:%s ' *)

      - name: ${{ env.IMAGE }} - Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.TARGET }}:${{ steps.meta-minimal.outputs.version }}
