name: build-docker

on:
  push:
    paths-ignore:
      - '.github/workflows/cmake-test.yml'
      - '.github/workflows/docker-cleanup.yml'

  workflow_dispatch:

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  # split this way so hopefully the cache is there between normal and minimal
  build-docker-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        # no point in more than base image supports
        # ignore 32-bit - 386, arm/v5, arm/v7
        # arm64 == arm64/v8
        platform: [amd64, arm64, ppc64le, riscv64, s390x]
        # platform: [amd64]
    env:
      registry: 'ghcr.io'
      package-name: ${{ case( startsWith(github.ref, 'refs/tags/v') || contains('["main", "dev", "unstable"]', github.ref_name), 'firestarr', 'cache' ) }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true

      - name: Login to container registry
        id: login
        uses: docker/login-action@v4
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Show values
        run: |
          echo "${{ env.registry }}"
          echo "${{ env.package-name }}"
          echo "${{ matrix.platform }}"

      - uses: ./.github/actions/docker-build-image
        id: build-firestarr
        with:
          target: firestarr
          registry: ${{ env.registry }}
          package-name: ${{ env.package-name }}
          platform: ${{ matrix.platform }}

      - uses: ./.github/actions/docker-build-image
        id: build-firestarr-minimal
        with:
          target: firestarr-minimal
          registry: ${{ env.registry }}
          package-name: ${{ env.package-name }}
          platform: ${{ matrix.platform }}

      - name: Set outputs
        run: |
          echo "registry=${{ env.registry }}" >> $GITHUB_OUTPUT
          echo "package-name=${{ env.package-name }}" >> $GITHUB_OUTPUT
          echo "platform=${{ matrix.platform }}" >> $GITHUB_OUTPUT

  merge-firestarr:
    needs: [build-docker-image]
    uses: ./.github/workflows/docker-merge-image.yml
    with:
      target: firestarr
      registry: ${{ needs.build-docker-image.outputs.registry }}
      package-name: ${{ needs.build-docker-image.outputs.package-name }}
      flavor: |
        latest=${{ case ( startsWith(github.ref, 'refs/tags/v'), 'auto', 'false' ) }}
        prefix=
        suffix=
      tags: |
        type=ref,event=pr
        type=ref,prefix=,suffix=,event=branch,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
        type=ref,prefix=,suffix=-latest,event=branch,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
        type=semver,pattern={{version}},prefix=,suffix=,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
        type=semver,pattern={{major}}.{{minor}},prefix=,suffix=,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

  merge-firestarr-minimal:
    needs: [build-docker-image]
    uses: ./.github/workflows/docker-merge-image.yml
    with:
      target: firestarr-minimal
      registry: ${{ needs.build-docker-image.outputs.registry }}
      package-name: ${{ needs.build-docker-image.outputs.package-name }}
      flavor: |
        latest=false
        prefix=
        suffix=-minimal
      tags: |
        type=ref,event=pr,prefix=,suffix=-minimal
        type=ref,prefix=,suffix=-minimal,event=branch,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
        type=ref,prefix=,suffix=-minimal-latest,event=branch,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
        type=semver,pattern={{version}},prefix=,suffix=-minimal,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
        type=semver,pattern={{major}}.{{minor}},prefix=,suffix=-minimal,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
        type=raw,value=minimal,prefix=,suffix=,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
        type=raw,value=minimal-latest,prefix=,suffix=,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
