name: build-docker

on:
  push:
    branches:
      - main
      - dev
      - unstable
    paths-ignore:
      - '.github/workflows/cmake-test.yml'
      - '.github/workflows/docker-cleanup.yml'

  workflow_dispatch:

jobs:
  build-docker-normal:
    uses: ./.github/workflows/build-docker-image.yml

  build-docker-minimal:
    needs: [build-docker-normal]
    uses: ./.github/workflows/build-docker-image.yml
    with:
      suffix: minimal
