name: cmake-test

on:
  push:
    paths-ignore:
      - '.github/**docker**'
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  cmake-test:
    runs-on: ${{ matrix.os }}-${{ matrix.os-version }}${{ case( matrix.os != 'macos' && matrix.target-cpu == 'arm64', '-arm', '' ) }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos, ubuntu, windows]
        compiler: [cl, clang++, g++]
        target-cpu: [arm64, x64]
        variant: [Release]
        include:
          - os: macos
            os-version: 14
            target-os: osx
          # HACK: latest doesn't work with -arm
          - os: ubuntu
            os-version: 24.04
            target-os: linux
          # FIX: this is building x64 exe not arm64
          # # HACK: latest doesn't work with -arm
          # - os: windows
          #   target-cpu: arm64
          #   os-version: 11
          #   target-os: windows
          - os: windows
            target-cpu: x64
            os-version: 2025-vs2026
            target-os: windows
          - compiler: clang++
            target-compiler: clang
          - compiler: cl
            target-compiler: cl
          - compiler: g++
            target-compiler: gcc
        exclude:
          - os: macos
            target-cpu: x64
          - os: macos
            compiler: cl
          - os: ubuntu
            compiler: cl
          - os: windows
            compiler: clang++
          - os: windows
            compiler: g++
          # FIX: this is building x64 exe not arm64
          - os: windows
            target-cpu: arm64
    env:
      CXX: ${{ matrix.compiler }}
      BUILD_SETUP: ""
      # HACK: -static makes windows work right now
      VCPKG_TARGET_TRIPLET: ${{ matrix.target-cpu }}-${{ matrix.target-os }}${{ case ( matrix.os == 'windows', '-static', '' ) }}
      VCPKG_DISABLE_METRICS: true
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      ARCHIVE_FORMAT: ${{ case( matrix.os == 'windows', '.zip', '.tar.gz' ) }}
      RELEASE_ARCHIVE: firestarr-${{ matrix.os }}-${{ matrix.target-cpu}}-${{ matrix.target-compiler }}-${{ matrix.variant }}
      BINARY: firestarr${{ case( matrix.os == 'windows', '.exe', '' ) }}

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: true

    - name: Install dependencies (macos gcc)
      if: ${{ matrix.os == 'macos' && matrix.target-compiler == 'gcc' }}
      run: |
        brew install -q gcc proj libgeotiff libtiff curl tbb
        GCC_VERSION=$(brew list --versions gcc | grep -oE '[0-9]+' | head -1)
        echo "GCC_VERSION=$GCC_VERSION" >> $GITHUB_ENV
        echo "CC=$(brew --prefix)/bin/gcc-${GCC_VERSION}" >> $GITHUB_ENV
        echo "CXX=$(brew --prefix)/bin/g++-${GCC_VERSION}" >> $GITHUB_ENV
        echo "BREW_PREFIX=$(brew --prefix)" >> $GITHUB_ENV
        echo "TBB_ROOT=$(brew --prefix tbb)" >> $GITHUB_ENV


    - name: Find build tools (windows)
      if: ${{ matrix.os == 'windows' }}
      run: |
        $VSWHERE = "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vswhere.exe"
        If(Test-Path "${VSWHERE}")
        {
            # detect shell to get msvcs
            $vsPath = &("${VSWHERE}") -property installationpath
        }
        If(${vsPath})
        {
            echo "Found path ${vsPath}"
        } else {
            $vsPath = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools"
            echo "Assuming path ${vsPath}"
        }
        $vars=(cmd /c """${vsPath}\\VC\\Auxiliary\\Build\\vcvarsall.bat"" amd64 > NUL && set")
        foreach ($v in $vars) {
          Add-Content -Path ${env:GITHUB_ENV} -Value "$v"
        }

    - uses: friendlyanon/setup-vcpkg@v1
      with:
        committish: 2025.12.12
        # getting a warning when cache exists, so just save/restore ourselves
        cache: false

    - name: Check VCPKG_DEFAULT_BINARY_CACHE
      run: |
        echo "VCPKG_DEFAULT_BINARY_CACHE = $VCPKG_DEFAULT_BINARY_CACHE"

    - uses: actions/cache@v5
      with:
        # vcpkg always builds release, so share cache between debug and release
        key: vcpkg-${{ matrix.os }}-${{ matrix.target-cpu}}-${{ matrix.target-compiler }}-${{ hashFiles('vcpkg.json', '.github/vcpkg_overlays/**') }}
        path: |
          ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}

    - name: Configure
      run: |
        cmake --preset ${{ matrix.variant }}

    - name: Run cmake --build --parallel --preset ${{ matrix.variant }}
      run: |
        echo "::add-matcher::.github/cmake-problem-matcher.json"
        cmake --build --parallel --preset ${{ matrix.variant }}

    - run: ./firestarr -h

    - name: Test
      run: |
        ctest --output-on-failure --preset ${{ matrix.variant }}

    - name: Test basic run
      run: ./firestarr dir_test 2024-06-03 58.81228184403946 -122.9117103995713 01:00 --ffmc 89.9 --dmc 59.5 --dc 450.9 --apcp_prev 0 -v --wx ./test/input/10N_50651/firestarr_10N_50651_wx.csv --output_date_offsets [1] --tz -5 --raster-root ./test/input/10N_50651/ --perim ./test/input/10N_50651/10N_50651.tif

    - name: Test grid up north
      run: ./firestarr test/output/north 2023-06-19 60.82328538629729 -115.70484253475514 19:00 --tz -8 --wx test/input/north/weather.csv --ffmc 83.5 --dmc 53.7 --dc 568.9 --apcp_prev 0 --raster-root test/input/empty_grids --perim test/input/north/perimeter.tif --output_date_offsets [1] --sim-area --deterministic -i

    - name: Test that this projection fails
      if: ${{ matrix.os == 'ubuntu' }}
      run: (! ./firestarr test/output/bad_projection 2023-10-03 58.81228184403946 -122.9117103995713 12:00 --ffmc 93.52 --dmc 18 --dc 409 --apcp_prev 0 --log logfile.txt --no-probability --deterministic -v -i -s --raster-root test/input/bad_projection --perim test/input/bad_projection/perim.tif --wx test/input/bad_projection/wx.csv --output_date_offsets "[1,2,3]" --tz -7)

    # rename so we can upload without archiving again
    - run: |
        mv build/firestarr${{ env.ARCHIVE_FORMAT }} build/${{ env.RELEASE_ARCHIVE }}${{ env.ARCHIVE_FORMAT }}

    - name: Upload artifact
      if: ${{ matrix.variant == 'Release' }}
      uses: actions/upload-artifact@v7
      with:
        path: build/${{ env.RELEASE_ARCHIVE }}${{ env.ARCHIVE_FORMAT }}
        archive: false
        retention-days: 30

  build-release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') || contains('["main", "dev", "unstable"]', github.ref_name) }}
    needs: [cmake-test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      # if '-' in tag then it's -alpha or similar
      IS_LATEST: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') }}
      # should just be !env.IS_LATEST but can't figure out syntax
      IS_PRERELEASE: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-') }}
      TAG: ${{ github.ref_name }}${{ case ( !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-'), '-latest', '' ) }}

    steps:
      # need checkout to delete release
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true

      - name: Delete existing tag
        if: ${{ env.IS_PRERELEASE }}
        run: gh release delete -y ${{ env.TAG }} --cleanup-tag || echo "Tag ${{ env.TAG }} does not exist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          skip-decompress: true

      - name: List artifacts
        run: |
          echo "=== All artifacts ==="
          find . -type f \( -name "*.tar.gz" -o -name "*.zip" \)

      - name: Publish Release
        uses: softprops/action-gh-release@v3
        with:
          name: "FireSTARR ${{ github.ref_name }}"
          tag_name: ${{ env.TAG }}
          target_commitish: ${{ github.sha }}
          body: |
            **Hash:** ${{ github.sha }}
            **Workflow run:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          make_latest: ${{ env.IS_LATEST }}
          prerelease: ${{ env.IS_PRERELEASE }}
          generate_release_notes: true
          files: |
            ./firestarr*/*.tar.gz
            ./firestarr*/*.zip
