name: docker-merge-image

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      package:
        required: true
        type: string
      flavor:
        required: true
        type: string
      tags:
        required: true
        type: string

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  merge:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true

      - name: Prepare environment
        run: |
          package=${{ inputs.package }}
          echo "CONTAINER_REGISTRY=${package%%\/*}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: ${{ inputs.target }} - Download digests
        uses: actions/download-artifact@v8
        with:
          path: ${{ runner.temp }}/digests-${{ inputs.target }}
          pattern: digests-${{ inputs.target }}-*
          merge-multiple: true

      - name: ${{ inputs.target }} - Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ inputs.package }}
          flavor: ${{ inputs.flavor }}
          tags: ${{ inputs.tags }}

      - name: ${{ inputs.target }} - Create manifest list and push
        working-directory: ${{ runner.temp }}/digests-${{ inputs.target }}
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ inputs.package }}@sha256:%s ' *)

      - name: ${{ inputs.target }} - Inspect image
        run: |
          docker buildx imagetools inspect ${{ inputs.package }}:${{ steps.meta.outputs.version }}

      - name: Set outputs
        run: |
          echo "target=${{ inputs.target }}" >> $GITHUB_OUTPUT
          echo "package=${{ inputs.package }}" >> $GITHUB_OUTPUT
